spring:
  # DB ?? ??
  datasource:
    url: jdbc:mariadb://localhost:3306/jh
    username: jh2
    password: tkfkd12dl!
    driver-class-name: org.mariadb.jdbc.Driver

  session:
    jdbc:
      initialize-schema: always

  #domain Set

  security:
    debug:
      mode : true


  devtools:
    livereload:
      enabled: false
  freemarker:
    cache: false


  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: NEVER


#log ??
logging:
  level:
    org:
      springframework:
        security=DEBUG:
      hibernate:
        SQL: debug
        type:
        descriptor:
          sql : trace


account:
  domain: localhost
  key : 92voKL6hlHBTr/TlpTRiPJ/udey58grzenZ8dJqz3VE=

